"""跨运行入口共享的稳定默认值。"""

DEFAULT_WEB_PORT = 1258

# 跨 Web/API/Agent/后台任务共享的功能开关默认值。调用方不得自行复制
# True/False，否则“未配置”状态会因入口不同而产生双轨语义。
DEFAULT_DISCOVERY_ENABLED = False
DEFAULT_INDEXER_SEARCH_ENABLED = True
DEFAULT_AGENT_LLM_ENABLED = False
DEFAULT_BOOL_CONFIG_VALUES: dict[str, bool] = {
    "DISCOVERY_ENABLED": DEFAULT_DISCOVERY_ENABLED,
    "INDEXER_SEARCH_ENABLED": DEFAULT_INDEXER_SEARCH_ENABLED,
    "AGENT_LLM_ENABLED": DEFAULT_AGENT_LLM_ENABLED,
}
DEFAULT_DOWNLOAD_TORRENT_RETENTION_DAYS = 0
MAX_DOWNLOAD_TORRENT_RETENTION_DAYS = 3650
